### ISSUE TITLE
How to train with a custom dataset?

### ISSUE THREAD

**Issue by lwhkop** [birdortyedi/fashion-image-inpainting#1]
Hello, I'm very interested in this work. But I want to use this model on my own dataset. Would you mind teaching me how to train with a custom dataset? What kind of labels do I need to train this model? And are there any pre-trained models I can download?

**Comment by birdortyedi** [comment]
Thank you for your interest! You need to write your custom data loader for your dataset, and to have irregular masks (see https://github.com/karfly/qd-imd). We are planning to share a pre-trained model for each dataset that we included.
