### ISSUE TITLE
X Train Creation

### ISSUE THREAD

**Issue by bluesky314** [birdortyedi/fashion-image-inpainting#5]
What is the function of 0.5 here? Is the area to be filled in given by 0.5 values?

`x_train = x_mask * y_train + (1.0 - x_mask) * 0.5`

**Comment by birdortyedi** [comment]
Yes, the missing pixels are filled with 0.5.

**Comment by bluesky314** [comment]
Ok so just to confirm x_train has 0.5 and x_mask is a binary map and has 1's at the area to be filled in?
