### ISSUE TITLE
Loading weights

### ISSUE THREAD

**Issue by bluesky314** [birdortyedi/fashion-image-inpainting#6]
Tried to load the weights_net_df2.pth weights given. Firstly had to rename dict items to remove 'module' from  parameter name stem but even then so getting Unexpected keys error'.
Here is how the loading was done and error:

```
from collections import OrderedDict
w=torch.load('weights_net_df2.pth')
new=OrderedDict({})

for key in w.keys():
  new_name=('.').join(key.split('.')[1:])
  new[new_name]=w[key]

net=Net()
net.load_state_dict(new)
```

Gives:

![image](https://user-images.githubusercontent.com/35393972/111067033-21d7c500-84e8-11eb-82f4-bf76fed0eeb2.png)

How to load weights correctly?

**Comment by birdortyedi** [comment]
`net.load_state_dict(torch.load(PATH))`

**Comment by bluesky314** [comment]
That does not work :

![image](https://user-images.githubusercontent.com/35393972/111067827-fce55100-84eb-11eb-8670-fb101e36c420.png)

Sometimes torch changes the stem name and thats why above the module stem was removed.

**Comment by birdortyedi** [comment]
Yes, I meant to do that after removing multi-gpu module.

**Comment by bluesky314** [comment]
That is what was done in the original post and it still the error shown of the extra attention weights.......

**Comment by bluesky314** [comment]
Sorry not fully getting you, what is the 'multi-gpu module' and how to remove it?

**Comment by bluesky314** [comment]
@birdortyedi Still struggling with this....
