### ISSUE TITLE
Size of x_mask

### ISSUE THREAD

**Issue by bluesky314** [birdortyedi/fashion-image-inpainting#7]
Tried to input x_mask as a single channel binary mask with 1's at the area to be filled in with size torch.Size([1, 1, 256, 256])
however got 

`RuntimeError: Given groups=1, weight of size [64, 3, 7, 7], expected input[1, 1, 256, 256] to have 3 channels, but got 1 channels instead`

What exactly is x_mask?

**Comment by birdortyedi** [comment]
You can stack the same binary mask in three channels, and use like this.
